<#
.SYNOPSIS
    Build APK tự động - File Transfer Android App
.DESCRIPTION
    Script này tự động:
    1. Kiểm tra Java
    2. Tải Android SDK command-line tools
    3. Cài đặt SDK platform và build tools
    4. Tải Gradle wrapper JAR
    5. Build file APK (debug)
    
    Không cần cài Android Studio!
    
.LINK
    https://developer.android.com/studio/command-line/sdkmanager
#>

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$AndroidHome = "$env:USERPROFILE\android-sdk"
$CmdlineToolsZip = "$AndroidHome\cmdline-tools.zip"
$CmdlineToolsDir = "$AndroidHome\cmdline-tools\latest"
$GradleVersion = "8.5"
$GradleJarUrl = "https://services.gradle.org/distributions/gradle-${GradleVersion}-bin.zip"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   BUILD APK - File Transfer Android    " -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# === Bước 1: Kiểm tra Java ===
Write-Host "[1/6] Kiểm tra Java..." -ForegroundColor Yellow
try {
    $javaVersion = java -version 2>&1
    if ($LASTEXITCODE -ne 0) { throw "Java not found" }
    Write-Host "  => OK: Java đã được cài đặt" -ForegroundColor Green
} catch {
    Write-Host "[!] Lỗi: Không tìm thấy Java!" -ForegroundColor Red
    Write-Host "    Hãy cài JDK 17 từ: https://adoptium.net/"
    exit 1
}
Write-Host ""

# === Bước 2: Tải Android SDK ===
Write-Host "[2/6] Kiểm tra Android SDK..." -ForegroundColor Yellow
if (-not (Test-Path "$CmdlineToolsDir\bin\sdkmanager.bat")) {
    Write-Host "  => Đang tải Android SDK command-line tools..."
    
    if (-not (Test-Path $AndroidHome)) { New-Item -ItemType Directory -Path $AndroidHome -Force | Out-Null }
    
    # Tải cmdline-tools
    $url = "https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip"
    Write-Host "  => URL: $url"
    try {
        Invoke-WebRequest -Uri $url -OutFile $CmdlineToolsZip -UseBasicParsing -TimeoutSec 120
    } catch {
        Write-Host "[!] Lỗi tải cmdline-tools. Thử link dự phòng..." -ForegroundColor Yellow
        $url = "https://dl.google.com/android/repository/commandlinetools-win-10406996_latest.zip"
        Invoke-WebRequest -Uri $url -OutFile $CmdlineToolsZip -UseBasicParsing -TimeoutSec 120
    }
    
    # Giải nén
    Write-Host "  => Đang giải nén..."
    Expand-Archive -Path $CmdlineToolsZip -DestinationPath "$AndroidHome\tmp" -Force
    
    # Di chuyển đúng cấu trúc thư mục
    if (Test-Path "$AndroidHome\tmp\cmdline-tools") {
        Move-Item -Path "$AndroidHome\tmp\cmdline-tools\*" -Destination $CmdlineToolsDir -Force
        Remove-Item -Path "$AndroidHome\tmp" -Recurse -Force
    }
    
    Remove-Item $CmdlineToolsZip -Force
    Write-Host "  => OK: Android SDK đã tải về" -ForegroundColor Green
} else {
    Write-Host "  => OK: Android SDK đã có sẵn" -ForegroundColor Green
}
Write-Host ""

# === Bước 3: Cài đặt SDK components ===
Write-Host "[3/6] Cài đặt SDK components..." -ForegroundColor Yellow
$env:ANDROID_HOME = $AndroidHome
$env:PATH = "$CmdlineToolsDir\bin;$env:PATH"

# Tạo file để accept license
New-Item -Path "$AndroidHome\licenses" -ItemType Directory -Force | Out-Null
"24333f8a63b6825ea9c5514f83c2829b004d1fee" | Set-Content -Path "$AndroidHome\licenses\android-sdk-license"
"84831b9409646a918e30573bab4c9c91346d8abd" | Set-Content -Path "$AndroidHome\licenses\android-sdk-preview-license"

# Tạo file yes để auto-accept
$yesFile = "$AndroidHome\yes.txt"
"y" * 100 | Set-Content -Path $yesFile

# Platform và build-tools cần thiết
$sdkManager = "$CmdlineToolsDir\bin\sdkmanager.bat"
$packages = @(
    "platforms;android-34",
    "build-tools;34.0.0"
)

foreach ($pkg in $packages) {
    $pkgName = $pkg -replace '.*;', ''
    Write-Host "  => Cài đặt $pkgName..." -ForegroundColor Gray
    & $sdkManager --sdk_root=$AndroidHome $pkg < $yesFile 2>&1 | Out-Null
}

Write-Host "  => OK: SDK components đã sẵn sàng" -ForegroundColor Green
Write-Host ""

# === Bước 4: Tạo local.properties ===
Write-Host "[4/6] Tạo local.properties..." -ForegroundColor Yellow
$localProps = Join-Path $ScriptDir "local.properties"
"# Auto-generated by build_apk.ps1" | Set-Content -Path $localProps
"# $(Get-Date)" | Add-Content -Path $localProps
"sdk.dir=$($AndroidHome -replace '\\', '/')" | Add-Content -Path $localProps
Write-Host "  => OK: local.properties đã tạo" -ForegroundColor Green
Write-Host ""

# === Bước 5: Tải Gradle wrapper JAR ===
Write-Host "[5/6] Kiểm tra Gradle wrapper..." -ForegroundColor Yellow
$gradleJar = Join-Path $ScriptDir "gradle\wrapper\gradle-wrapper.jar"
if (-not (Test-Path $gradleJar) -or (Get-Item $gradleJar).Length -eq 0) {
    Write-Host "  => Đang tải Gradle wrapper..."
    
    # Tải Gradle distribution để lấy wrapper JAR
    $gradleZip = "$env:TEMP\gradle.zip"
    try {
        Invoke-WebRequest -Uri $GradleJarUrl -OutFile $gradleZip -UseBasicParsing -TimeoutSec 120
    } catch {
        Write-Host "[!] Lỗi tải Gradle. Vui lòng kiểm tra kết nối mạng." -ForegroundColor Red
        exit 1
    }
    
    # Giải nén và copy gradle-wrapper.jar
    $extractDir = "$env:TEMP\gradle-extract"
    if (Test-Path $extractDir) { Remove-Item $extractDir -Recurse -Force }
    Expand-Archive -Path $gradleZip -DestinationPath $extractDir -Force
    
    $gradleDir = Get-ChildItem $extractDir | Where-Object { $_.PSIsContainer } | Select-Object -First 1
    $sourceJar = Join-Path $gradleDir.FullName "lib\gradle-wrapper-*.jar"
    $wrapperJar = Get-ChildItem $sourceJar | Select-Object -First 1
    
    if ($wrapperJar) {
        Copy-Item $wrapperJar.FullName $gradleJar -Force
        Write-Host "  => OK: Gradle wrapper JAR đã tải" -ForegroundColor Green
    } else {
        Write-Host "[!] Không tìm thấy gradle-wrapper JAR trong distribution." -ForegroundColor Yellow
        Write-Host "    Thử build với Gradle có sẵn..."
    }
    
    # Dọn dẹp
    Remove-Item $gradleZip -Force -ErrorAction SilentlyContinue
    Remove-Item $extractDir -Recurse -Force -ErrorAction SilentlyContinue
} else {
    Write-Host "  => OK: Gradle wrapper đã có sẵn" -ForegroundColor Green
}
Write-Host ""

# === Bước 6: Build APK ===
Write-Host "[6/6] Build APK..." -ForegroundColor Yellow
Write-Host "  => Đang build (có thể mất 2-5 phút lần đầu)..." -ForegroundColor Gray

cd $ScriptDir

# Chạy gradlew
if (Test-Path $gradleJar) {
    & .\gradlew.bat assembleDebug --no-daemon 2>&1
    $buildResult = $LASTEXITCODE
} else {
    Write-Host "[!] Gradle wrapper không khả dụng. Thử dùng lệnh gradle trực tiếp..." -ForegroundColor Yellow
    gradle assembleDebug 2>&1
    $buildResult = $LASTEXITCODE
}

Write-Host ""

if ($buildResult -eq 0) {
    # Tìm file APK
    $apkPath = Get-ChildItem -Path "$ScriptDir\app\build\outputs\apk\debug\*.apk" | Select-Object -First 1
    if ($apkPath) {
        $apkSize = "{0:N2}" -f ($apkPath.Length / 1MB)
        Write-Host "========================================" -ForegroundColor Green
        Write-Host "   BUILD THÀNH CÔNG!                    " -ForegroundColor Green
        Write-Host "========================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "  File APK: $($apkPath.FullName)" -ForegroundColor Cyan
        Write-Host "  Kích thước: $apkSize MB" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "  Cách cài đặt:" -ForegroundColor White
        Write-Host "  1. Copy file APK sang điện thoại" -ForegroundColor Gray
        Write-Host "  2. Mở file APK trên điện thoại" -ForegroundColor Gray
        Write-Host "  3. Cho phép cài ứng dụng từ nguồn không xác định" -ForegroundColor Gray
        Write-Host ""
    } else {
        Write-Host "[!] Build thành công nhưng không tìm thấy file APK." -ForegroundColor Yellow
        Write-Host "    Kiểm tra thư mục: app\build\outputs\apk\" -ForegroundColor Yellow
    }
} else {
    Write-Host "[!] BUILD THẤT BẠI (mã lỗi: $buildResult)" -ForegroundColor Red
    Write-Host "    Kiểm tra log bên trên để biết chi tiết." -ForegroundColor Red
    exit 1
}
